(function() {var implementors = {};
implementors["parity_tokio_ipc"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"parity_tokio_ipc/struct.SecurityAttributes.html\" title=\"struct parity_tokio_ipc::SecurityAttributes\">SecurityAttributes</a>",synthetic:true,types:["parity_tokio_ipc::unix_permissions::SecurityAttributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"parity_tokio_ipc/struct.Endpoint.html\" title=\"struct parity_tokio_ipc::Endpoint\">Endpoint</a>",synthetic:true,types:["parity_tokio_ipc::Endpoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"parity_tokio_ipc/struct.RemoteId.html\" title=\"struct parity_tokio_ipc::RemoteId\">RemoteId</a>",synthetic:true,types:["parity_tokio_ipc::RemoteId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"parity_tokio_ipc/struct.Incoming.html\" title=\"struct parity_tokio_ipc::Incoming\">Incoming</a>",synthetic:true,types:["parity_tokio_ipc::Incoming"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"parity_tokio_ipc/struct.IpcConnection.html\" title=\"struct parity_tokio_ipc::IpcConnection\">IpcConnection</a>",synthetic:true,types:["parity_tokio_ipc::IpcConnection"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
